### ISSUE TITLE
Cara ganti template cover dan halaman pengesahan.

### ISSUE THREAD

**Issue by dehamzah** [gtrdp/template-skripsi#1]
Saya masih baru menggunakan latex. 
dan mau coba fork project ini untuk template skripsi kuliah saya.
tapi bagaimana cara ganti template cover dan halaman pengesahannya ya?
saya lihat di template-skripsi.tex cuma ada variabel2 yang bisa diganti.

**Comment by gtrdp** [comment]
kalau mau ganti layout halaman, harus edit file `jtetiskripsi.cls`

untuk template cover, edit mulai di baris `241`
untuk template halaman pengesahan, edit mulai di baris `272`

semoga membantu

**Comment by dehamzah** [comment]
okee, iyanih sudah bisa.

thankyou..
